name: Docker

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/time2block:latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build --tag $IMAGE_NAME .
      - run: docker run --rm $IMAGE_NAME task test
