name: Docker

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/time2block:latest
      TARGET_BRANCH: refs/heads/main
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: ${{ github.event_name == 'push' && github.ref == env.TARGET_BRANCH }}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' && github.ref == env.TARGET_BRANCH }}
          tags: ${{ env.IMAGE_NAME }}
