name: Docker

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TARGET_BRANCH: refs/heads/main
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true
      - run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
        id: version
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: ${{ github.event_name == 'push' && (github.ref == env.TARGET_BRANCH || startsWith(github.ref, 'refs/tags/')) }}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' && (github.ref == env.TARGET_BRANCH || startsWith(github.ref, 'refs/tags/')) }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/time2block:latest
            ${{ vars.DOCKERHUB_USERNAME }}/time2block:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
