name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno lint
      - run: deno fmt --check
      - run: deno check src/
      # make sure the deno.lock doesn't get changed silently
      - run: deno install --frozen=true
      - run: deno task test:coverage:lcov
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
